- name: configure cart host
  hosts: cart
  become: yes
  tasks:
    - name: disable dnf module and enable node js 20
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: install nodejs 20
      ansible.builtin.dnf:
        name: nodejs
        state: present
    
    - name: create system cart roboshop
      ansible.builtin.user:
        name: roboshop
        system: true
        home: /app
        shell: /sbin/nologin
        comment: "roboshop system user"

    - name: ansible delete app directory
      ansible.builtin.file:
        path: /app
        state: absent

    - name: create app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: delete cart zip file
      ansible.builtin.file:
        path: /tmp/cart.zip
        state: absent
      
    - name: download cart
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip
        dest: /tmp/cart.zip

    - name: unzip the file
      ansible.builtin.unarchive:
        src: /tmp/cart.zip
        dest: /app 
        remote_src: yes

    - name: install dependencies
      community.general.npm:
        path: /app

    - name: copy cart service
      ansible.builtin.copy:
        src: cart.service
        dest: /etc/systemd/system/cart.service

    - name: start cart service
      ansible.builtin.service:
        name: cart
        state: restarted
        enabled: yes