- name: configure catalogue host
  hosts: catalogue
  become: yes
  tasks:
    - name: disable dnf module and enable node js 20
      ansible.builtin.command: dnf module disable nodejs -y

    - name: install nodejs 20
      ansible.builtin.dnf:
        name: nodejs
        state: present
    
    - name: create system user roboshop
      ansible.builtin.user:
        name: roboshop
        system: true
        home: /app
        shell: /sbin/app
        comment: "roboshop system user"

    - name: create app directory
      ansible.builtin.file:
        path: /app
        state: directory
      
    - name: download catalogue
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
        dest: /tmp/catalogue.zip

    - name: unzip the file
      ansible.builtin.unarchive:
        src: /tmp/catalogue.zip
        dest: /app 
        remote_src: yes

    - name: install dependencies
      community.general.npm:
        path: /app

    - name: copy catalogue service
      ansible.builtin.copy:
        src: catalogue.service
        dest: /etc/systemd/system/catalogue.service
    

