[mongodb]
mongodb-dev.vinoddevops.online

[catalogue]
catalogue-dev.vinoddevops.online

[redis]
redis-dev.vinoddevops.online

[user]
user-dev.vinoddevops.online

[cart]
cart-dev.vinoddevops.online

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321
MONGODB_HOST=mongodb-dev.vinoddevops.online
redis_host=redis-dev.vinoddevops.online
user_host=user-dev.vinoddevops.online
catalogue_host=catalogue-dev.vinoddevops.online