[mongodb]
mongodb-dev.vinoddevops.online

[catalogue]
catalogue-dev.vinoddevops.online

[redis]
redis-dev.vinoddevops.online

[user]
user-dev.vinoddevops.online

[cart]
cart-dev.vinoddevops.online

[mysql]
mysql-dev.vinoddevops.online

[shipping]
shipping-dev.vinoddevops.online

[rabbitmq]
rabbitmq-dev.vinoddevops.online

[payment]
payment-dev.vinoddevops.online

[frontend]
roboshop-dev.vinoddevops.online

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321
MONGODB_HOST=mongodb-dev.vinoddevops.online
redis_host=redis-dev.vinoddevops.online
user_host=user-dev.vinoddevops.online
catalogue_host=catalogue-dev.vinoddevops.online
cart_hist=cart-dev.vinoddevops.online
mysql_host=mysql-dev.vinoddevops.online
shipping_host=shipping-dev.vinoddevops.online
rabbitmq_host=rabbitmq-dev.vinoddevops.online
payment_host=payment-dev.vinoddevops.online