- name: configure rabbit mq server
  hosts: rabbitmq
  become: yes
  tasks:
  - name: copy repo file
    ansible.builtin.copy:
      src: rabbitmq.repo
      dest: /etc/yum.repos.d/rabbitmq.repo

  - name: install rabbitmq server
    ansible.builtin.dnf:
      name: rabbitmq-server
      state: present

  - name: enable and restart rabbit mq server
    ansible.builtin.service:
     name: rabbitmq-server
     state: restarted
     enabled: yes

  - name: create rabbit mq user
    community.rabbitmq.rabbitmq_user:
      user: roboshop
      password: roboshop123
      topic_permissions:
      - vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*