- name: create ec2 and route53 records
  hosts: all
  connection: local

  vars:
    sg_id: sg-0869d702361b71486
    im_id: ami-0220d79f3f480ecf5
    env: dev
    instances:
    - mongodb
    - catalogue
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      instance_type: t3.micro
      image_id: "{{ im_id }}"
      security_group: "{{ sg_id }}"
      name: "{{ item }}-{{ env }}"
      tags:
        Project: roboshop
        Component: "{{ item }}"
        Environment: "{{ env }}"
        Name: "{{ item }}-{{ env }}"
    loop: "{{ instances }}"
    register: "{{ ec2_output }}"
  - name: print the ec2 output
    ansible.builtin.debug:
     msg: "{{ ec2_output }}"