- name: configure shipping module
  hosts: shipping
  become: yes
  tasks:
  - name: install maven
    ansible.builtin.dnf:
     name: maven
     state: present

   
  - name: create system user roboshop
    ansible.builtin.user:
      name: roboshop
      system: true
      home: /app
      shell: /sbin/nologin
      comment: "roboshop system user"

  - name: ansible delete app directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: delete shipping zip file
    ansible.builtin.file:
      path: /tmp/shipping.zip
      state: absent
      
  - name: download shipping
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
      dest: /tmp/shipping.zip

  - name: unzip the file
    ansible.builtin.unarchive:
      src: /tmp/shipping.zip
      dest: /app 
      remote_src: yes

  - name: install dependencies
    ansible.builtin.command:  mvn clean package
    args:
      chdir: /app

  - name: install dependencies
    ansible.builtin.command:  mv target/shipping-1.0.jar shipping.jar 
    args:
      chdir: /app

  - name: copy the service file
    ansible.builtin.template:
      src: shipping.service
      dest: /etc/systemd/system/shipping.service

  - name: Reload systemd daemon
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: install mysql client
    ansible.builtin.dnf:
      name: mysql
      state: present

  - name: install dependencies
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - PyMySQL
    - cryptography

  - name: import shipping data
    community.mysql.mysql_db:
      state: import
      name: all
      login_host: "{{ mysql_host }}"
      login_password: RoboShop@1
      target: "{{ item }}"
    loop: 
    - /app/db/schema.sql
    - /app/db/app-user.sql
    - /app/db/master-data.sql

  - name: start and enale shipping module
    ansible.builtin.service:
     name: shipping
     state: restarted
     enabled: yes